# Run from this folder in a fresh PowerShell window.
#
# Produces trusight_breakdowns.html AND publishes it to
# arcane/public/reports/ip_deep_dive.html — which is the file the live site
# links to from arcane/src/app/page.tsx.
#
# THE PUBLISH STEP USED TO BE MANUAL AND UNRECORDED. That is why the site served
# a May build for four months while the markdown was corrected underneath it:
# PR #103 fixed the One Piece prose in the source and the live page never
# changed, because nobody knew a copy step existed. Automating it here is the
# whole point of this edit.
#
# Every build stamps a provenance footer (docs/provenance_convention.md) so the
# next person can tell, from the file alone, what made it and from which commit.

$ErrorActionPreference = 'Stop'

$SourceMd   = 'trusight_breakdowns_scratch.md'
$BuildHtml  = 'trusight_breakdowns.html'
$PublishTo  = '../../arcane/public/reports/ip_deep_dive.html'
$PageTitle  = 'IP Deep Dive: 19 Licensing Candidates'

# Try pandoc on PATH first; fall back to the default install location if needed
$pandoc = (Get-Command pandoc -ErrorAction SilentlyContinue).Source
if (-not $pandoc) {
    $candidate = 'C:\Program Files\Pandoc\pandoc.exe'
    if (Test-Path $candidate) {
        $pandoc = $candidate
    } else {
        Write-Error "pandoc not found on PATH and not at $candidate. Open a fresh PowerShell window (so PATH refreshes after the winget install) and try again."
        exit 1
    }
}

# ─── Provenance footer ──────────────────────────────────────────────────────
# Emitted by the build, never hand-typed. A provenance block someone has to
# remember to update is wrong within a month, and a stale one is worse than no
# block at all because it gets believed.

$pandocVersion = (& $pandoc --version | Select-Object -First 1)
$sourceSha = try { (& git log -1 --format=%h -- $SourceMd 2>$null) } catch { '' }
if (-not $sourceSha) { $sourceSha = 'unknown' }
$dirty = try { if ((& git status --porcelain $SourceMd 2>$null)) { ' (UNCOMMITTED CHANGES)' } else { '' } } catch { '' }
$builtAt = (Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ')

$footer = @"
<hr style="margin-top:3em" />
<div style="font-family:ui-monospace,Consolas,monospace;font-size:9pt;color:#606070;line-height:1.6">
<strong>Provenance</strong><br />
Generated by : make_html.ps1 ($pandocVersion)<br />
Source&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : pitch/report/$SourceMd @ $sourceSha$dirty<br />
Stylesheet&nbsp;&nbsp; : pitch/report/pdf_style.css<br />
Built&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;: $builtAt<br />
Rebuild&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; : cd pitch/report ; ./make_html.ps1<br />
<br />
Figures in this report were authored into the source markdown, not bound to a
live query. See docs/report_rendering_design.md for the plan to change that, and
docs/data_capture_hardening_plan.md (work item I) for known errors in this
edition.
</div>
"@

$footerFile = [System.IO.Path]::GetTempFileName() + '.html'
Set-Content -Path $footerFile -Value $footer -Encoding UTF8

Write-Host "Using pandoc at: $pandoc"
Write-Host "Converting $SourceMd -> $BuildHtml (source @ $sourceSha$dirty) ..."

& $pandoc `
    $SourceMd `
    -o $BuildHtml `
    --standalone `
    --embed-resources `
    --css 'pdf_style.css' `
    --include-after-body $footerFile `
    --metadata "pagetitle=$PageTitle"

$pandocExit = $LASTEXITCODE
Remove-Item $footerFile -ErrorAction SilentlyContinue

if ($pandocExit -ne 0) {
    Write-Error "pandoc exited with code $pandocExit"
    exit $pandocExit
}

$size = (Get-Item $BuildHtml).Length / 1MB
Write-Host ("Done. $BuildHtml created ({0:N1} MB)." -f $size)

# ─── Publish ────────────────────────────────────────────────────────────────
# The site links to arcane/public/reports/ip_deep_dive.html. Copying here means
# a corrected source cannot silently fail to reach readers.

$publishDir = Split-Path $PublishTo -Parent
if (Test-Path $publishDir) {
    Copy-Item $BuildHtml $PublishTo -Force
    Write-Host "Published -> $PublishTo"
    Write-Host "Commit that file and deploy for the change to reach trusightdata.ai."
} else {
    Write-Warning "Publish target $publishDir not found; skipped. $BuildHtml is still built."
}

Write-Host "For a PDF: open the HTML in a browser, then Ctrl+P -> Save as PDF."
