-- game_registry population batch 1: 48 PHB-2024 canonical subclasses + 3 vocabulary_lexicon seed rows
-- Posture: 2024 names canonical; prior/2014 names live in aliases (load-bearing reception JOIN keys).
-- is_srd = FALSE for ALL 48 (conservative legal posture: 2024 text is redesigned; SRD-5.2 coverage
--   unverified; under-claiming is the safe stance with the rights-holder as prospect). SRD-5.1
--   lineage recorded in design_history_note where applicable. Registry stores NO mechanical text.
-- power_source_axis / role_axis = NULL (demand-driven backfill, deferred). fantasy_flavor_tags = [].
--
-- RE-RUN SAFETY: these are plain INSERTs (not idempotent). Run once on empty tables.
-- To rebuild from scratch, uncomment the two TRUNCATEs below first (destructive — wipes the
-- tables, including any analytical-axis backfill done since seed). Default = do nothing on re-run.
-- TRUNCATE TABLE `dnd-trends-index.game_registry.subclasses`;
-- TRUNCATE TABLE `dnd-trends-index.game_registry.vocabulary_lexicon`;

INSERT INTO `dnd-trends-index.game_registry.subclasses`
(subclass_id, canonical_name, aliases, parent_class, source_book, source_book_short, edition, publication_year, is_srd, power_source_axis, role_axis, fantasy_flavor_tags, design_history_note, last_verified, is_current_canonical, lineage_id, lifecycle_status)
VALUES
-- ===== Barbarian =====
("barbarian_path_of_the_berserker","Path of the Berserker",["Path of the Berserker","Berserker","Berserker Barbarian"],"Barbarian","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Player's Handbook (2014); 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture (no mechanical text stored).",DATE "2026-05-15",TRUE,"barbarian_berserker","current_2024"),
("barbarian_path_of_the_wild_heart","Path of the Wild Heart",["Path of the Wild Heart","Wild Heart","Path of the Totem Warrior","Totem Warrior","Totem Barbarian"],"Barbarian","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Path of the Totem Warrior in PHB 2014 (in SRD 5.1, CC-BY-4.0); renamed Path of the Wild Heart in PHB 2024. Community/reception data predominantly uses 'Totem Warrior'.",DATE "2026-05-15",TRUE,"barbarian_wild_heart","current_2024"),
("barbarian_path_of_the_world_tree","Path of the World Tree",["Path of the World Tree","World Tree","World Tree Barbarian"],"Barbarian","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"New subclass introduced in PHB 2024 (playtested in 2022-2024 Unearthed Arcana); no prior published edition.",DATE "2026-05-15",TRUE,"barbarian_world_tree","current_2024"),
("barbarian_path_of_the_zealot","Path of the Zealot",["Path of the Zealot","Zealot","Zealot Barbarian"],"Barbarian","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Xanathar's Guide to Everything (2017); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"barbarian_zealot","current_2024"),
-- ===== Bard =====
("bard_college_of_dance","College of Dance",["College of Dance","Dance Bard"],"Bard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"New subclass introduced in PHB 2024 (playtested in 2022-2024 Unearthed Arcana); no prior published edition.",DATE "2026-05-15",TRUE,"bard_dance","current_2024"),
("bard_college_of_glamour","College of Glamour",["College of Glamour","Glamour Bard"],"Bard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Xanathar's Guide to Everything (2017); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"bard_glamour","current_2024"),
("bard_college_of_lore","College of Lore",["College of Lore","Lore Bard"],"Bard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"bard_lore","current_2024"),
("bard_college_of_valor","College of Valor",["College of Valor","Valor Bard"],"Bard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014 (Lore was the SRD 5.1 bard subclass, not Valor); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"bard_valor","current_2024"),
-- ===== Cleric ===== (2024 PHB reprints 4 of the 2014 domains; Knowledge/Nature/Tempest/Death etc. remain backward-compatible but unreprinted)
("cleric_life_domain","Life Domain",["Life Domain","Life Cleric"],"Cleric","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). 2024 PHB reprints only Life/Light/Trickery/War; other 2014 domains backward-compatible but unreprinted.",DATE "2026-05-15",TRUE,"cleric_life","current_2024"),
("cleric_light_domain","Light Domain",["Light Domain","Light Cleric"],"Cleric","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Life was the SRD cleric domain).",DATE "2026-05-15",TRUE,"cleric_light","current_2024"),
("cleric_trickery_domain","Trickery Domain",["Trickery Domain","Trickery Cleric"],"Cleric","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1.",DATE "2026-05-15",TRUE,"cleric_trickery","current_2024"),
("cleric_war_domain","War Domain",["War Domain","War Cleric"],"Cleric","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1.",DATE "2026-05-15",TRUE,"cleric_war","current_2024"),
-- ===== Druid =====
("druid_circle_of_the_land","Circle of the Land",["Circle of the Land","Land Druid"],"Druid","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"druid_land","current_2024"),
("druid_circle_of_the_moon","Circle of the Moon",["Circle of the Moon","Moon Druid"],"Druid","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Land was the SRD druid circle).",DATE "2026-05-15",TRUE,"druid_moon","current_2024"),
("druid_circle_of_the_sea","Circle of the Sea",["Circle of the Sea","Sea Druid"],"Druid","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"New subclass introduced in PHB 2024 (playtested in 2022-2024 Unearthed Arcana); no prior published edition.",DATE "2026-05-15",TRUE,"druid_sea","current_2024"),
("druid_circle_of_the_stars","Circle of the Stars",["Circle of the Stars","Stars Druid","Starry Form"],"Druid","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Tasha's Cauldron of Everything (2020); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"druid_stars","current_2024"),
-- ===== Fighter =====
("fighter_battle_master","Battle Master",["Battle Master","Battlemaster","Battle Master Fighter"],"Fighter","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Champion was the SRD fighter archetype).",DATE "2026-05-15",TRUE,"fighter_battle_master","current_2024"),
("fighter_champion","Champion",["Champion","Champion Fighter"],"Fighter","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"fighter_champion","current_2024"),
("fighter_eldritch_knight","Eldritch Knight",["Eldritch Knight","Eldritch Knight Fighter","EK"],"Fighter","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1.",DATE "2026-05-15",TRUE,"fighter_eldritch_knight","current_2024"),
("fighter_psi_warrior","Psi Warrior",["Psi Warrior","Psi Warrior Fighter","Psionic Warrior"],"Fighter","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Tasha's Cauldron of Everything (2020); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"fighter_psi_warrior","current_2024"),
-- ===== Monk =====
("monk_warrior_of_mercy","Warrior of Mercy",["Warrior of Mercy","Way of Mercy","Mercy Monk"],"Monk","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Way of Mercy in Tasha's Cauldron of Everything (2020); renamed Warrior of Mercy in PHB 2024. Reception data predominantly uses 'Way of Mercy'.",DATE "2026-05-15",TRUE,"monk_mercy","current_2024"),
("monk_warrior_of_shadow","Warrior of Shadow",["Warrior of Shadow","Way of Shadow","Way of the Shadow","Shadow Monk"],"Monk","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Way of Shadow in PHB 2014; renamed Warrior of Shadow in PHB 2024. Reception data predominantly uses 'Way of Shadow' / 'Shadow Monk'.",DATE "2026-05-15",TRUE,"monk_shadow","current_2024"),
("monk_warrior_of_the_elements","Warrior of the Elements",["Warrior of the Elements","Way of the Four Elements","Four Elements Monk","Elements Monk"],"Monk","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Way of the Four Elements in PHB 2014; renamed and substantially reworked to Warrior of the Elements in PHB 2024. Reception data predominantly uses 'Way of the Four Elements'.",DATE "2026-05-15",TRUE,"monk_elements","current_2024"),
("monk_warrior_of_the_open_hand","Warrior of the Open Hand",["Warrior of the Open Hand","Way of the Open Hand","Open Hand Monk"],"Monk","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Way of the Open Hand in PHB 2014 (in SRD 5.1, CC-BY-4.0); renamed Warrior of the Open Hand in PHB 2024. Reception data predominantly uses 'Way of the Open Hand'.",DATE "2026-05-15",TRUE,"monk_open_hand","current_2024"),
-- ===== Paladin =====
("paladin_oath_of_devotion","Oath of Devotion",["Oath of Devotion","Devotion Paladin"],"Paladin","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"paladin_devotion","current_2024"),
("paladin_oath_of_glory","Oath of Glory",["Oath of Glory","Glory Paladin"],"Paladin","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Tasha's Cauldron of Everything (2020); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"paladin_glory","current_2024"),
("paladin_oath_of_the_ancients","Oath of the Ancients",["Oath of the Ancients","Ancients Paladin","Green Knight"],"Paladin","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Devotion was the SRD paladin oath).",DATE "2026-05-15",TRUE,"paladin_ancients","current_2024"),
("paladin_oath_of_vengeance","Oath of Vengeance",["Oath of Vengeance","Vengeance Paladin"],"Paladin","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1.",DATE "2026-05-15",TRUE,"paladin_vengeance","current_2024"),
-- ===== Ranger =====
("ranger_beast_master","Beast Master",["Beast Master","Beastmaster","Beast Master Ranger","Beast Master Conclave"],"Ranger","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Hunter was the SRD ranger archetype). 2024 canonical spelling is two words 'Beast Master'.",DATE "2026-05-15",TRUE,"ranger_beast_master","current_2024"),
("ranger_fey_wanderer","Fey Wanderer",["Fey Wanderer","Fey Wanderer Ranger"],"Ranger","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Tasha's Cauldron of Everything (2020); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"ranger_fey_wanderer","current_2024"),
("ranger_gloom_stalker","Gloom Stalker",["Gloom Stalker","Gloomstalker","Gloom Stalker Ranger"],"Ranger","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Xanathar's Guide to Everything (2017); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"ranger_gloom_stalker","current_2024"),
("ranger_hunter","Hunter",["Hunter","Hunter Ranger","Hunter Conclave"],"Ranger","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"ranger_hunter","current_2024"),
-- ===== Rogue =====
("rogue_arcane_trickster","Arcane Trickster",["Arcane Trickster","Arcane Trickster Rogue"],"Rogue","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1 (Thief was the SRD rogue archetype).",DATE "2026-05-15",TRUE,"rogue_arcane_trickster","current_2024"),
("rogue_assassin","Assassin",["Assassin","Assassin Rogue"],"Rogue","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; revised in PHB 2024. Not in SRD 5.1.",DATE "2026-05-15",TRUE,"rogue_assassin","current_2024"),
("rogue_soulknife","Soulknife",["Soulknife","Soul Knife","Soulknife Rogue"],"Rogue","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in Tasha's Cauldron of Everything (2020); revised in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"rogue_soulknife","current_2024"),
("rogue_thief","Thief",["Thief","Thief Rogue"],"Rogue","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated in PHB 2014; 2014 version in SRD 5.1 (CC-BY-4.0). Revised in PHB 2024; is_srd=FALSE is a conservative posture.",DATE "2026-05-15",TRUE,"rogue_thief","current_2024"),
-- ===== Sorcerer =====
("sorcerer_aberrant_sorcery","Aberrant Sorcery",["Aberrant Sorcery","Aberrant Mind","Aberrant Mind Sorcerer","Aberrant Sorcerer"],"Sorcerer","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Aberrant Mind in Tasha's Cauldron of Everything (2020); renamed Aberrant Sorcery in PHB 2024. Reception data predominantly uses 'Aberrant Mind'.",DATE "2026-05-15",TRUE,"sorcerer_aberrant","current_2024"),
("sorcerer_clockwork_sorcery","Clockwork Sorcery",["Clockwork Sorcery","Clockwork Soul","Clockwork Soul Sorcerer"],"Sorcerer","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Clockwork Soul in Tasha's Cauldron of Everything (2020); renamed Clockwork Sorcery in PHB 2024. Reception data predominantly uses 'Clockwork Soul'.",DATE "2026-05-15",TRUE,"sorcerer_clockwork","current_2024"),
("sorcerer_draconic_sorcery","Draconic Sorcery",["Draconic Sorcery","Draconic Bloodline","Draconic Bloodline Sorcerer","Draconic Sorcerer","Dragon Sorcerer"],"Sorcerer","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Draconic Bloodline in PHB 2014 (in SRD 5.1, CC-BY-4.0); renamed Draconic Sorcery in PHB 2024. Reception data predominantly uses 'Draconic Bloodline'.",DATE "2026-05-15",TRUE,"sorcerer_draconic","current_2024"),
("sorcerer_wild_magic_sorcery","Wild Magic Sorcery",["Wild Magic Sorcery","Wild Magic","Wild Magic Sorcerer"],"Sorcerer","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as Wild Magic in PHB 2014; renamed Wild Magic Sorcery in PHB 2024. Not in SRD 5.1 (Draconic Bloodline was the SRD sorcerer origin). Reception data predominantly uses 'Wild Magic'.",DATE "2026-05-15",TRUE,"sorcerer_wild_magic","current_2024"),
-- ===== Warlock =====
("warlock_archfey_patron","Archfey Patron",["Archfey Patron","The Archfey","Archfey Warlock","Archfey"],"Warlock","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as The Archfey in PHB 2014; renamed Archfey Patron in PHB 2024. Not in SRD 5.1 (The Fiend was the SRD warlock patron). Reception data predominantly uses 'Archfey'.",DATE "2026-05-15",TRUE,"warlock_archfey","current_2024"),
("warlock_celestial_patron","Celestial Patron",["Celestial Patron","The Celestial","Celestial Warlock","Celestial"],"Warlock","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as The Celestial in Xanathar's Guide to Everything (2017); renamed Celestial Patron in PHB 2024. Not in SRD.",DATE "2026-05-15",TRUE,"warlock_celestial","current_2024"),
("warlock_fiend_patron","Fiend Patron",["Fiend Patron","The Fiend","Fiend Warlock","Fiend"],"Warlock","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as The Fiend in PHB 2014 (in SRD 5.1, CC-BY-4.0); renamed Fiend Patron in PHB 2024. Reception data predominantly uses 'Fiend'.",DATE "2026-05-15",TRUE,"warlock_fiend","current_2024"),
("warlock_great_old_one_patron","Great Old One Patron",["Great Old One Patron","The Great Old One","Great Old One Warlock","Great Old One","GOO Warlock","GOOlock"],"Warlock","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as The Great Old One in PHB 2014; renamed Great Old One Patron in PHB 2024. Not in SRD 5.1. Reception data uses 'Great Old One' / 'GOOlock'.",DATE "2026-05-15",TRUE,"warlock_great_old_one","current_2024"),
-- ===== Wizard =====
("wizard_abjurer","Abjurer",["Abjurer","School of Abjuration","Abjuration Wizard","Abjuration"],"Wizard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as School of Abjuration in PHB 2014; renamed Abjurer in PHB 2024. Not in SRD 5.1 (School of Evocation was the SRD wizard tradition). Reception data predominantly uses 'School of Abjuration'.",DATE "2026-05-15",TRUE,"wizard_abjuration","current_2024"),
("wizard_diviner","Diviner",["Diviner","School of Divination","Divination Wizard","Divination"],"Wizard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as School of Divination in PHB 2014; renamed Diviner in PHB 2024. Not in SRD 5.1. Reception data predominantly uses 'School of Divination'.",DATE "2026-05-15",TRUE,"wizard_divination","current_2024"),
("wizard_evoker","Evoker",["Evoker","School of Evocation","Evocation Wizard","Evocation"],"Wizard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as School of Evocation in PHB 2014 (in SRD 5.1, CC-BY-4.0); renamed Evoker in PHB 2024. Reception data predominantly uses 'School of Evocation'.",DATE "2026-05-15",TRUE,"wizard_evocation","current_2024"),
("wizard_illusionist","Illusionist",["Illusionist","School of Illusion","Illusion Wizard","Illusion"],"Wizard","Player's Handbook (2024)","PHB2024","5e-2024",2024,FALSE,NULL,NULL,[],"Originated as School of Illusion in PHB 2014; renamed Illusionist in PHB 2024. Not in SRD 5.1. Reception data predominantly uses 'School of Illusion'.",DATE "2026-05-15",TRUE,"wizard_illusion","current_2024");

INSERT INTO `dnd-trends-index.game_registry.vocabulary_lexicon`
(term, register, safe_for_deliverables, safe_translation, history_note)
VALUES
("Arcane / Divine / Primal (spell-list source framework)","official_retired",FALSE,"spell origin / class spell identity","Spell-list source framework from One D&D 2022-2023 Unearthed Arcana (Crawford, class-identity rationale). Reverted at UA7 (Sept 2023) after fan rejection; not present in final PHB 2024. Treat as retired official vocabulary, never current canon. NEVER surface untranslated to WoTC."),
("Striker / Defender / Controller / Leader (party roles)","4e_edition",FALSE,"damage-focused / protection-focused / battlefield-control / support roles","4th Edition (2008) party-role taxonomy. Persists in optimizer folksonomy but is not 5e official vocabulary. Internal-eval / JOIN use only; translate before any deliverable."),
("Brute (monster role)","4e_edition",FALSE,"high-hit-point, low-accuracy aggressive monster profile","4th Edition monster role. Useful internal shorthand for encounter / eHP modeling; not 5e official vocabulary. Translate before any deliverable.");
