„0import csv

# Auto-Generated External Collisions
EXTERNAL_COLLISIONS = {
    "Baldur's Gate 3": [
        "Ability Score Improvement",
        "Abjuration School",
        "Acolyte",
        "Actor",
        "Alert",
        "Arcane Archer",
        "Arcane Trickster",
        "Assassin",
        "Athlete",
        "Battle Master",
        "Beast Master",
        "Berserker",
        "Bladesinging",
        "Champion",
        "Charger",
        "Charlatan",
        "Circle of Spores",
        "Circle of the Land",
        "Circle of the Moon",
        "Circle of the Stars",
        "College of Glamour",
        "College of Lore",
        "College of Swords",
        "College of Valour",
        "Conjuration School",
        "Criminal",
        "Crossbow Expert",
        "Death Domain",
        "Defensive Duelist",
        "Divination School",
        "Divine Soul",
        "Draconic Bloodline",
        "Dual Wielder",
        "Dungeon Delver",
        "Durable",
        "Eldritch Knight",
        "Elemental Adept",
        "Enchantment School",
        "Entertainer",
        "Evocation School",
        "Folk Hero",
        "Gloom Stalker",
        "Great Weapon Master",
        "Guild Artisan",
        "Haunted One",
        "Heavily Armoured",
        "Heavy Armor Master",
        "Hunter",
        "Illusion School",
        "Knowledge Domain",
        "Life Domain",
        "Light Domain",
        "Lightly Armoured",
        "Lucky",
        "Mage Slayer",
        "Magic Initiate",
        "Martial Adept",
        "Medium Armour Master",
        "Mobile",
        "Moderately Armoured",
        "Nature Domain",
        "Necromancy School",
        "Noble",
        "Oath of Devotion",
        "Oath of Vengeance",
        "Oath of the Ancients",
        "Oath of the Crown",
        "Oathbreaker",
        "Outlander",
        "Path of Giants",
        "Performer",
        "Polearm Master",
        "Resilient",
        "Ritual Caster",
        "Sage",
        "Savage Attacker",
        "Sentinel",
        "Shadow Magic",
        "Sharpshooter",
        "Shield Master",
        "Skilled",
        "Soldier",
        "Spell Sniper",
        "Storm Sorcery",
        "Swarmkeeper",
        "Swashbuckler",
        "Tavern Brawler",
        "Tempest Domain",
        "The Archfey",
        "The Fiend",
        "The Great Old One",
        "The Hexblade",
        "Thief",
        "Tough",
        "Transmutation School",
        "Trickery Domain",
        "Urchin",
        "War Caster",
        "War Domain",
        "Way of Shadow",
        "Way of the Drunken Master",
        "Way of the Four Elements",
        "Way of the Open Hand",
        "Weapon Master",
        "Wild Magic",
        "Wildheart"
    ],
    "Diablo": [
        "Barbarian",
        "Sorcerer",
        "Sorceress",
        "Rogue",
        "Druid",
        "Necromancer",
        "Monk",
        "Paladin"
    ],
    "Pathfinder": [
        "Barbarian",
        "Bard",
        "Cleric",
        "Druid",
        "Fighter",
        "Monk",
        "Paladin",
        "Ranger",
        "Rogue",
        "Sorcerer",
        "Wizard",
        "Alchemist",
        "Shaman",
        "Magus",
        "Gunslinger",
        "Summoner",
        "Bloodrager",
        "Brawler",
        "Hunter",
        "Slayer",
        "Swashbuckler",
        "Investigator",
        "Skald"
    ],
    "Skyrim": [
        "Battlemage",
        "Spellsword",
        "Assassin",
        "Paladin",
        "Ranger"
    ],
    "Warhammer": [
        "Witch Hunter",
        "Assassin",
        "Wizard",
        "Warrior Priest",
        "Ranger",
        "Scout"
    ],
    "World of Warcraft": [
        "Paladin",
        "Warrior",
        "Monk",
        "Rogue",
        "Priest",
        "Mage",
        "Warlock",
        "Druid",
        "Hunter",
        "Holy Paladin",
        "Protection Paladin",
        "Retribution Paladin",
        "Brewmaster Monk",
        "Mistweaver Monk",
        "Windwalker Monk"
    ],
    "Generic": [
        "Water",
        "Fire",
        "Air",
        "Earth",
        "Strength",
        "Dexterity",
        "Constitution",
        "Intelligence",
        "Wisdom",
        "Charisma",
        "Attack",
        "Defense",
        "Speed",
        "Level",
        "Class",
        "Race",
        "Background",
        "Feat",
        "Spell",
        "Item",
        "Monster",
        "NPC",
        "Build",
        "Guide",
        "5e",
        "Dnd",
        "D&D"
    ],
    "Professions": [
        "Captain",
        "Merchant",
        "Messenger",
        "Scholar",
        "Scout",
        "Stalker",
        "Nomad",
        "Philosopher",
        "Physician",
        "Savage",
        "Blacksmith",
        "Bomber",
        "Celebrity",
        "Chieftain",
        "Outlaw",
        "Athlete",
        "Awakened"
    ],
    "Ambiguous Entities": [
        "Champion",
        "Warden",
        "Raven Queen",
        "Telekinesis",
        "Hunter",
        "Beast",
        "Shadow",
        "Light",
        "Tempest",
        "Life",
        "Death"
    ]
}

OUTPUT_FILE = 'external_collisions_report.csv'

def export_report():
    rows = []
    for category, terms in EXTERNAL_COLLISIONS.items():
        for term in terms:
            rows.append({"Category": category, "Term": term})
            
    # Sort by Category then Term
    rows.sort(key=lambda x: (x['Category'], x['Term']))
    
    keys = ["Category", "Term"]
    try:
        with open(OUTPUT_FILE, 'w', newline='', encoding='utf-8') as f:
            writer = csv.DictWriter(f, fieldnames=keys)
            writer.writeheader()
            writer.writerows(rows)
        print(f"Successfully exported {len(rows)} terms to {OUTPUT_FILE}")
    except Exception as e:
        print(f"Error writing CSV: {e}")

if __name__ == "__main__":
    export_report()
„0"(5ea7c1b525e148ee9cb36b57c32852aa3816ac0223file:///c:/Users/Yorri/.gemini/export_collisions.py:file:///c:/Users/Yorri/.gemini